dotnet-core/Projects/YY.AspNetCore/YY.AspNetCore.WebDemo/Controllers/TitleListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using X.PagedList.Mvc;
using X.PagedList;
using YY.EF.Core.Interface;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using YY.EF.Core.Model;
using System.Linq.Expressions;
using YY.Framework;
using Microsoft.AspNetCore.Authorization;

namespace YY.AspNetCore.WebDemo.Controllers
{
    //[Authorize]
    public class TitleListController : Controller
    {
        private int pageSize = 20;
        private IImageService _imageService = null;
        private readonly ILogger<TitleListController> _logger;
        private readonly IConfiguration _configuration;
        public TitleListController(ILogger<TitleListController> logger, IConfiguration configuration,IImageService imageService)
        {
            _logger = logger;
            _configuration = configuration;
            _imageService = imageService;
        }
        public ActionResult Index(string searchString, string group, int? pageIndex)
        {
            #region 查询条件
            //searchString = base.HttpContext.Request.Form["searchString"];
            Expression<Func<ImageTitle, bool>> funcWhere = null;

            if (!string.IsNullOrWhiteSpace(searchString))
            {
                funcWhere = funcWhere.And(c => c.ImageTitle1.Contains(searchString));
                base.ViewBag.SearchString = searchString;
            }
            if (!string.IsNullOrWhiteSpace(group))
            {
                funcWhere = funcWhere.And(c => c.ImageGroup.Contains(group));
                base.ViewBag.Group = group;
            }
            funcWhere = funcWhere.And(c => c.ImageGroup != null && c.TotalCount != null);
            #endregion

            #region 排序
            Expression<Func<ImageTitle, int>> funOrderby = c => c.Id;
            #endregion

            int index = pageIndex ?? 1;

            PageResult<ImageTitle> imageTitleList = _imageService.QueryPage(funcWhere, pageSize, index, funOrderby, true);
            StaticPagedList<ImageTitle> pageList = new StaticPagedList<ImageTitle>(imageTitleList.DataList, index, pageSize, imageTitleList.TotalCount);

            return View(pageList);
        }
        public ActionResult Delete(int? id)
        {
            int index = id ?? -1;
            _imageService.Delete<ImageTitle>(index);
            return RedirectToAction("Index");
        }
    }
}

dotnet-core/Projects/YY.AspNetCore/YY.AspNetCore.WebDemo/Views/TitleList/Index.cshtml
@using YY.EF.Core.Model;
@using X.PagedList.Mvc;
@using X.PagedList;
@using X.PagedList.Mvc.Core;

@model StaticPagedList<ImageTitle>

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("Index", "TitleList"))
{
    <p>
        <a href="~/Views/ImageName/Index">友情链接</a>
        <br>
        Find by Condition Key Words:
        @Html.TextBox("searchString", ViewBag.SearchString as string, new { @class = "form-control", @Style = "display:inline" })
        GroupName:
        @Html.TextBox("group", ViewBag.Group as string, new { @class = "form-control", @Style = "display:inline" })
        @*@Html.Submit("查询")*@
        <input type="submit" value="查询" />
    </p>
    <div id="partialajaxlist">
        <table class="table">
            <tr>
                <th>Id</th>
                <th>标题</th>
                <th width="100px">数量</th>
                <th width="100px">类别</th>
                <th>Action</th>
                <th>@*@Html.ActionLink("价格", "Index", new { orderBy = ViewBag.OrderBy, searchString = ViewBag.SearchString, page = 1 })*@</th>
            </tr>
            @*前后混编，前后分离 MVVM vue *@
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @*//强类型 可以展示display*@
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        <a href="~/ImageShow/index/?title=@item.ImageTitle1.Trim()&group=@item.ImageGroup.Trim()">@item.ImageTitle1-@item.ImageGroup</a>
                    </td>
                    <td>
                        @item.TotalCount
                    </td>
                    <td>
                        <a href="~/TitleList/index/?group=@item.ImageGroup.Trim()">@item.ImageGroup</a>
                    </td>
                    <td>
                        <a href="~/ImageShow/Index/?title=@item.ImageTitle1.Trim()&group=@item.ImageGroup">Details</a>|
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                    </td>
                    @*<input type="button" value="go">*@
                </tr>
            }
        </table>
        @*@Html.Br()*@
        <br>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, pageIndex => Url.Action("Index",
        new { pageIndex, searchString = ViewBag.SearchString, group = ViewBag.Group }))
        @*@Html.PagedListPager(Model, pageIndex => $"/ImageName/Index?pageIndex={pageIndex}&searchString={base.ViewBag.SearchString}")*@
    </div>
}